### ISSUE TITLE
Always treat REF as `major_allele` and ALT as `minor_allele` 

### ISSUE THREAD

**Issue by biona001** [OpenMendel/BGEN.jl#17]
Similar to #16, is there a way to always read the ALT allele (ATCG letter) and the REF allele regardless of which one is the minor allele?

I believe `major_allele` and `minor_allele` first checks which ALT/REF is less frequent, before assigning one as the minor allele. 

Here's a test data:
[Archive 2.zip](https://github.com/OpenMendel/BGEN.jl/files/6496086/Archive.2.zip)

MWE
```julia
using BGEN, VCFTools

# import VCF data (always read ALT as minor allele)
Gtrue, sampleID, record_chr, record_pos, record_ids, record_ref, 
    record_alt = convert_gt(Float64, "target.typedOnly.masked.vcf.gz",
    trans=true, save_snp_info=true)

# import BGEN and look at 2nd marker
b = Bgen("target.typedOnly.masked.bgen")
variants = parse_variants(b; from_bgen_start=true)
v = variants[2]
minor_allele_dosage!(b, v)

# VCF and BGEN disagree
major_allele(v), minor_allele(v) # this outputs ("G", "T")
record_ref[2], record_alt[2] # this outputs ("T", ["G"]) where ALT is a vector because it is possible to have >1 ALT allele

```

**Comment by kose-y** [comment]
For reference allele ordering, please use the ordering in `alleles(v::Variant)`.

**Comment by biona001** [comment]
thanks!
