### ISSUE TITLE
Individual ID extracted from wrong column

### ISSUE THREAD

**Issue by olivierlabayle** [OpenMendel/BGEN.jl#28]
Hi,

When reading BGEN files, I think the sample id is currently extracted from the wrong column. According to [this documentation](https://www.cog-genomics.org/plink/2.0/formats#sample), the column ID_2 corresponds to the individual ID. I think the origin might be [this function](https://github.com/OpenMendel/BGEN.jl/blob/c4bd6ed88813a726304635af68ccdf7e057dc19d/src/sample.jl#L18).

Potential fix? replace [1] by [2]

**Comment by kose-y** [comment]
Thanks for the report. Changed to read from column 2 if both ID_1 and ID_2 exist. It will still read from the first column otherwise.

**Comment by olivierlabayle** [comment]
Thank you for that!
