### ISSUE TITLE
Typo for haplotype documentation

### ISSUE THREAD

**Issue by biona001** [OpenMendel/BGEN.jl#6]
"On the other hand, if the data are phased, probabilities!(b, v)[i, j] represents the probability that haplotype (i - 1) ÷ p + 1 has allele (i - 1) % p + 1"

Surely there are typos here? If `i = 1`, then haplotype `1` has allele `1` with probability `probabilities!(b, v)[i, j]`? I can't understand how to parse extract haplotypes for each sample

**Comment by kose-y** [comment]
Thanks, I had to be a little bit more precise there. 

"On the other hand, if the data are phased, `probabilities!(b, v)[i, j]` represents the probability that haplotype `(i - 1) ÷ n_alleles + 1` has allele `(i - 1) % n_alleles + 1` for sample `j`, where `n_alleles` is the number of alleles."

For example:
```julia
b2 = Bgen(BGEN.datadir("complex.bgen"))
vs = parse_variants(b2)
p = probabilities!(b2, vs[3])
```

    4×4 Array{Float64,2}:
       1.0  0.0  1.0  1.0
       0.0  1.0  0.0  0.0
     NaN    0.0  1.0  0.0
     NaN    1.0  0.0  1.0

This variant has two possible alleles (allele 1: "A" and allele 2: "G"), and the all the samples are dipoids except for the first one, which is monoploid. 

It corresponds to a line of VCF file:

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample_0        sample_1        sample_2        sample_3
01      3       V3      A       G       .       .       .       GT:HP   0:1,0   1|1:0,1,0,1     0|0:1,0,1,0     0|1:1,0,0,1
```

So the first sample is monoploid of A, the second sample is homozygote A|A, the third sample is homozygote G|G, and the last sample is a heterozygote A|G (phased). 

Does it make sense to you?

**Comment by biona001** [comment]
Thank you very much. That helps tremendously.
